# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.cache/wt [current_project]
set_property parent.project_path D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/new/Part2.vhd
  D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/new/Part3.vhd
}
read_ip -quiet D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
set_property used_in_implementation false [get_files -all d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc]
set_property is_locked true [get_files D:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Part3 -part xc7z020clg484-1


write_checkpoint -force -noxdef Part3.dcp

catch { report_utilization -file Part3_utilization_synth.rpt -pb Part3_utilization_synth.pb }
