# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
# IP: The module: 'c_shift_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProjects/ECE524_PRELAB4/ECE524_PRELAB4.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
