# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/xfft_0_1/xfft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0}]
